/**
 * Real IPL team rosters for 2025 and 2026 seasons.
 * Maps team IDs to arrays of player objects with auction/retention prices.
 * Player names should match ESPN player database (longName field).
 *
 * Prices are in crores (INR). Sources:
 *   - IPL 2025 mega auction (Nov 24-25, 2024, Jeddah)
 *   - IPL 2026 mini auction (Dec 16, 2025, Abu Dhabi)
 *   - Official IPLT20, ESPNCricinfo, Olympics.com
 */

export interface IPLRosterPlayer {
  name: string;
  price: number;      // in crores (e.g., 27.0 for Rishabh Pant)
  retained?: boolean;  // true if retained pre-auction, not bought at auction
}

export interface IPLRoster {
  teamId: string;
  teamName: string;
  shortName: string;
  players: IPLRosterPlayer[];
}

// ---------------------------------------------------------------------------
// IPL 2026 Rosters (after Dec 2025 mini auction)
//
// Prices carry forward from IPL 2025 retention/auction unless the player was
// re-auctioned or traded in the 2026 cycle.  Players bought at the 2026 mini
// auction have their 2026 auction price.
// ---------------------------------------------------------------------------

export const IPL_2026_ROSTERS: IPLRoster[] = [
  {
    teamId: "csk",
    teamName: "Chennai Super Kings",
    shortName: "CSK",
    players: [
      // Retained from 2025
      { name: "MS Dhoni", price: 4.0, retained: true },
      { name: "Ruturaj Gaikwad", price: 18.0, retained: true },
      { name: "Shivam Dube", price: 12.0, retained: true },
      // Traded in from RR
      { name: "Sanju Samson", price: 18.0, retained: true },
      // Retained (2025 auction buys kept)
      { name: "Noor Ahmad", price: 10.0, retained: true },
      { name: "Khaleel Ahmed", price: 4.80, retained: true },
      { name: "Nathan Ellis", price: 2.0, retained: true },
      { name: "Jamie Overton", price: 1.50, retained: true },
      { name: "Anshul Kamboj", price: 3.40, retained: true },
      { name: "Shreyas Gopal", price: 0.30, retained: true },
      { name: "Mukesh Choudhary", price: 0.30, retained: true },
      { name: "Gurjapneet Singh", price: 2.20, retained: true },
      { name: "Ramakrishna Ghosh", price: 0.30, retained: true },
      { name: "Dewald Brevis", price: 2.20, retained: true },
      { name: "Ayush Mhatre", price: 0.30, retained: true },
      { name: "Urvil Patel", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Prashant Veer", price: 14.20 },
      { name: "Kartik Sharma", price: 14.20 },
      { name: "Rahul Chahar", price: 5.20 },
      { name: "Akeal Hosein", price: 2.0 },
      { name: "Matt Henry", price: 2.0 },
      { name: "Matthew Short", price: 1.50 },
      { name: "Sarfaraz Khan", price: 0.75 },
      { name: "Zak Foulkes", price: 0.75 },
      { name: "Aman Khan", price: 0.40 },
    ],
  },
  {
    teamId: "dc",
    teamName: "Delhi Capitals",
    shortName: "DC",
    players: [
      // Retained from 2025
      { name: "Axar Patel", price: 16.50, retained: true },
      { name: "Kuldeep Yadav", price: 13.25, retained: true },
      { name: "KL Rahul", price: 14.0, retained: true },
      { name: "Mitchell Starc", price: 11.75, retained: true },
      { name: "Tristan Stubbs", price: 10.0, retained: true },
      { name: "Abishek Porel", price: 4.0, retained: true },
      { name: "T Natarajan", price: 10.75, retained: true },
      { name: "Karun Nair", price: 0.50, retained: true },
      { name: "Ashutosh Sharma", price: 3.80, retained: true },
      { name: "Mukesh Kumar", price: 8.0, retained: true },
      { name: "Sameer Rizvi", price: 0.95, retained: true },
      { name: "Dushmantha Chameera", price: 0.75, retained: true },
      { name: "Vipraj Nigam", price: 0.50, retained: true },
      { name: "Madhav Tiwari", price: 0.40, retained: true },
      { name: "Ajay Mandal", price: 0.30, retained: true },
      { name: "Tripurana Vijay", price: 0.30, retained: true },
      // Traded in from RR
      { name: "Nitish Rana", price: 4.20, retained: true },
      // 2026 mini auction buys
      { name: "Auqib Nabi Dar", price: 8.40 },
      { name: "Pathum Nissanka", price: 4.0 },
      { name: "David Miller", price: 2.0 },
      { name: "Ben Duckett", price: 2.0 },
      { name: "Lungi Ngidi", price: 2.0 },
      { name: "Kyle Jamieson", price: 2.0 },
      { name: "Prithvi Shaw", price: 0.75 },
      { name: "Sahil Parikh", price: 0.30 },
    ],
  },
  {
    teamId: "gt",
    teamName: "Gujarat Titans",
    shortName: "GT",
    players: [
      // Retained from 2025
      { name: "Rashid Khan", price: 18.0, retained: true },
      { name: "Shubman Gill", price: 16.50, retained: true },
      { name: "Jos Buttler", price: 15.75, retained: true },
      { name: "Mohammed Siraj", price: 12.25, retained: true },
      { name: "Kagiso Rabada", price: 10.75, retained: true },
      { name: "Prasidh Krishna", price: 9.50, retained: true },
      { name: "Sai Sudharsan", price: 8.50, retained: true },
      { name: "Washington Sundar", price: 3.20, retained: true },
      { name: "Rahul Tewatia", price: 4.0, retained: true },
      { name: "Shahrukh Khan", price: 4.0, retained: true },
      { name: "Glenn Phillips", price: 2.0, retained: true },
      { name: "Sai Kishore", price: 2.0, retained: true },
      { name: "Ishant Sharma", price: 0.75, retained: true },
      { name: "Jayant Yadav", price: 0.75, retained: true },
      { name: "Manav Suthar", price: 0.30, retained: true },
      { name: "Nishant Sindhu", price: 0.30, retained: true },
      { name: "Anuj Rawat", price: 0.30, retained: true },
      { name: "Kulwant Khejroliya", price: 0.30, retained: true },
      { name: "Gurnoor Brar", price: 0.30, retained: true },
      { name: "Kumar Kushagra", price: 0.30, retained: true },
      { name: "Arshad Khan", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Jason Holder", price: 7.0 },
      { name: "Tom Banton", price: 2.0 },
      { name: "Ashok Sharma", price: 0.90 },
      { name: "Luke Wood", price: 0.75 },
    ],
  },
  {
    teamId: "kkr",
    teamName: "Kolkata Knight Riders",
    shortName: "KKR",
    players: [
      // Retained from 2025
      { name: "Rinku Singh", price: 13.0, retained: true },
      { name: "Sunil Narine", price: 12.0, retained: true },
      { name: "Varun Chakravarthy", price: 12.0, retained: true },
      { name: "Harshit Rana", price: 4.0, retained: true },
      { name: "Ramandeep Singh", price: 4.0, retained: true },
      { name: "Angkrish Raghuvanshi", price: 0.30, retained: true },
      { name: "Ajinkya Rahane", price: 1.50, retained: true },
      { name: "Anukul Roy", price: 0.30, retained: true },
      { name: "Manish Pandey", price: 0.75, retained: true },
      { name: "Rovman Powell", price: 1.50, retained: true },
      { name: "Umran Malik", price: 0.75, retained: true },
      { name: "Vaibhav Arora", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Cameron Green", price: 25.20 },
      { name: "Matheesha Pathirana", price: 18.0 },
      { name: "Mustafizur Rahman", price: 9.20 },
      { name: "Andre Russell", price: 12.0, retained: true },
      { name: "Finn Allen", price: 2.0 },
      { name: "Rachin Ravindra", price: 2.0 },
      { name: "Tim Seifert", price: 1.50 },
      { name: "Akash Deep", price: 1.0 },
      { name: "Rahul Tripathi", price: 0.75 },
      { name: "Tejasvi Singh", price: 3.0 },
      { name: "Prashant Solanki", price: 0.30 },
      { name: "Kartik Tyagi", price: 0.30 },
      { name: "Sarthak Ranjan", price: 0.30 },
    ],
  },
  {
    teamId: "lsg",
    teamName: "Lucknow Super Giants",
    shortName: "LSG",
    players: [
      // Retained from 2025
      { name: "Rishabh Pant", price: 27.0, retained: true },
      { name: "Nicholas Pooran", price: 21.0, retained: true },
      { name: "Mayank Yadav", price: 11.0, retained: true },
      { name: "Avesh Khan", price: 9.75, retained: true },
      { name: "Ayush Badoni", price: 4.0, retained: true },
      { name: "Mitchell Marsh", price: 3.40, retained: true },
      { name: "Aiden Markram", price: 2.0, retained: true },
      { name: "Mohammed Shami", price: 10.0, retained: true },
      { name: "Abdul Samad", price: 4.20, retained: true },
      { name: "Shahbaz Ahmed", price: 2.40, retained: true },
      { name: "Mohsin Khan", price: 4.0, retained: true },
      { name: "Arjun Tendulkar", price: 0.30, retained: true },
      { name: "Arshin Kulkarni", price: 0.30, retained: true },
      { name: "Himmat Singh", price: 0.30, retained: true },
      { name: "Manimaran Siddharth", price: 0.75, retained: true },
      { name: "Matthew Breetzke", price: 0.75, retained: true },
      { name: "Prince Yadav", price: 0.30, retained: true },
      { name: "Akash Singh", price: 0.30, retained: true },
      { name: "Digvesh Rathi", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Josh Inglis", price: 8.60 },
      { name: "Wanindu Hasaranga", price: 2.0 },
      { name: "Anrich Nortje", price: 2.0 },
      { name: "Mukul Choudhary", price: 2.60 },
      { name: "Akshat Raghuwanshi", price: 2.20 },
      { name: "Naman Tiwari", price: 1.0 },
    ],
  },
  {
    teamId: "mi",
    teamName: "Mumbai Indians",
    shortName: "MI",
    players: [
      // Retained from 2025
      { name: "Jasprit Bumrah", price: 18.0, retained: true },
      { name: "Hardik Pandya", price: 16.35, retained: true },
      { name: "Suryakumar Yadav", price: 16.35, retained: true },
      { name: "Rohit Sharma", price: 16.30, retained: true },
      { name: "Tilak Varma", price: 8.0, retained: true },
      { name: "Trent Boult", price: 12.50, retained: true },
      { name: "Will Jacks", price: 5.25, retained: true },
      { name: "Deepak Chahar", price: 9.25, retained: true },
      { name: "Ryan Rickelton", price: 1.0, retained: true },
      { name: "Naman Dhir", price: 5.25, retained: true },
      { name: "Robin Minz", price: 0.65, retained: true },
      { name: "Mitchell Santner", price: 2.0, retained: true },
      { name: "Corbin Bosch", price: 0.75, retained: true },
      { name: "AM Ghazanfar", price: 4.80, retained: true },
      { name: "Raj Bawa", price: 0.30, retained: true },
      { name: "Ashwani Kumar", price: 0.30, retained: true },
      { name: "Raghu Sharma", price: 0.50, retained: true },
      // Traded in
      { name: "Shardul Thakur", price: 4.0, retained: true },
      { name: "Sherfane Rutherford", price: 1.50, retained: true },
      // 2026 mini auction buys
      { name: "Quinton de Kock", price: 1.0 },
      { name: "Atharva Ankolekar", price: 0.30 },
      { name: "Mohammad Izhar", price: 0.30 },
      { name: "Danish Malewar", price: 0.30 },
      { name: "Mayank Rawat", price: 0.30 },
      { name: "Mayank Markande", price: 0.30 },
    ],
  },
  {
    teamId: "pbks",
    teamName: "Punjab Kings",
    shortName: "PBKS",
    players: [
      // Retained from 2025
      { name: "Shreyas Iyer", price: 26.75, retained: true },
      { name: "Arshdeep Singh", price: 18.0, retained: true },
      { name: "Yuzvendra Chahal", price: 18.0, retained: true },
      { name: "Marcus Stoinis", price: 11.0, retained: true },
      { name: "Marco Jansen", price: 7.0, retained: true },
      { name: "Lockie Ferguson", price: 2.0, retained: true },
      { name: "Nehal Wadhera", price: 4.20, retained: true },
      { name: "Prabhsimran Singh", price: 4.0, retained: true },
      { name: "Shashank Singh", price: 4.0, retained: true },
      { name: "Priyansh Arya", price: 3.80, retained: true },
      { name: "Harpreet Brar", price: 1.50, retained: true },
      { name: "Azmatullah Omarzai", price: 2.40, retained: true },
      { name: "Musheer Khan", price: 0.30, retained: true },
      { name: "Harnoor Singh Pannu", price: 0.30, retained: true },
      { name: "Mitch Owen", price: 1.0, retained: true },
      { name: "Pyla Avinash", price: 0.30, retained: true },
      { name: "Suryansh Shedge", price: 0.30, retained: true },
      { name: "Vishnu Vinod", price: 0.95, retained: true },
      { name: "Vyshak Vijaykumar", price: 1.80, retained: true },
      { name: "Xavier Bartlett", price: 0.80, retained: true },
      { name: "Yash Thakur", price: 1.60, retained: true },
      // 2026 mini auction buys
      { name: "Ben Dwarshuis", price: 4.40 },
      { name: "Cooper Connolly", price: 3.0 },
      { name: "Vishal Nishad", price: 0.30 },
      { name: "Pravin Dubey", price: 0.30 },
    ],
  },
  {
    teamId: "rr",
    teamName: "Rajasthan Royals",
    shortName: "RR",
    players: [
      // Retained from 2025
      { name: "Yashasvi Jaiswal", price: 18.0, retained: true },
      { name: "Riyan Parag", price: 14.0, retained: true },
      { name: "Shimron Hetmyer", price: 11.0, retained: true },
      { name: "Jofra Archer", price: 12.50, retained: true },
      { name: "Dhruv Jurel", price: 14.0, retained: true },
      { name: "Ravindra Jadeja", price: 16.0 }, // traded from CSK
      { name: "Sam Curran", price: 11.0 }, // traded from CSK
      { name: "Vaibhav Suryavanshi", price: 1.10, retained: true },
      { name: "Tushar Deshpande", price: 6.50, retained: true },
      { name: "Sandeep Sharma", price: 1.50 },
      { name: "Donovan Ferreira", price: 1.00 }, // traded from DC
      { name: "Kwena Maphaka", price: 1.50, retained: true },
      { name: "Nandre Burger", price: 3.50, retained: true },
      { name: "Shubham Dubey", price: 0.80, retained: true },
      { name: "Kunal Rathore", price: 0.30, retained: true },
      { name: "Yudhvir Singh Charak", price: 0.35, retained: true },
      { name: "Lhuan-dre Pretorius", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Ravi Bishnoi", price: 7.20 },
      { name: "Adam Milne", price: 2.40 },
      { name: "Sushant Mishra", price: 0.90 },
      { name: "Ravi Singh", price: 0.95 },
      { name: "Kuldeep Sen", price: 0.75 },
      { name: "Vignesh Puthur", price: 0.30 },
      { name: "Yash Raj Punja", price: 0.30 },
      { name: "Aman Rao", price: 0.30 },
      { name: "Brijesh Sharma", price: 0.30 },
    ],
  },
  {
    teamId: "rcb",
    teamName: "Royal Challengers Bengaluru",
    shortName: "RCB",
    players: [
      // Retained from 2025
      { name: "Virat Kohli", price: 21.0, retained: true },
      { name: "Rajat Patidar", price: 11.0, retained: true },
      { name: "Phil Salt", price: 11.50, retained: true },
      { name: "Josh Hazlewood", price: 12.50, retained: true },
      { name: "Yash Dayal", price: 5.0, retained: true },
      { name: "Tim David", price: 3.0, retained: true },
      { name: "Krunal Pandya", price: 5.75, retained: true },
      { name: "Bhuvneshwar Kumar", price: 10.75, retained: true },
      { name: "Jitesh Sharma", price: 11.0, retained: true },
      { name: "Devdutt Padikkal", price: 2.0, retained: true },
      { name: "Suyash Sharma", price: 2.60, retained: true },
      { name: "Swapnil Singh", price: 0.50, retained: true },
      { name: "Romario Shepherd", price: 1.50, retained: true },
      { name: "Jacob Bethell", price: 2.60, retained: true },
      { name: "Nuwan Thushara", price: 1.60, retained: true },
      { name: "Rasikh Dar Salam", price: 6.0, retained: true },
      { name: "Abhinandan Singh", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Venkatesh Iyer", price: 7.0 },
      { name: "Mangesh Yadav", price: 5.20 },
      { name: "Jacob Duffy", price: 2.0 },
      { name: "Jordan Cox", price: 0.75 },
      { name: "Vicky Ostwal", price: 0.30 },
      { name: "Vihaan Malhotra", price: 0.30 },
      { name: "Kanishk Chouhan", price: 0.30 },
    ],
  },
  {
    teamId: "srh",
    teamName: "Sunrisers Hyderabad",
    shortName: "SRH",
    players: [
      // Retained from 2025
      { name: "Heinrich Klaasen", price: 23.0, retained: true },
      { name: "Pat Cummins", price: 18.0, retained: true },
      { name: "Travis Head", price: 14.0, retained: true },
      { name: "Abhishek Sharma", price: 14.0, retained: true },
      { name: "Ishan Kishan", price: 11.25, retained: true },
      { name: "Nitish Kumar Reddy", price: 6.0, retained: true },
      { name: "Harshal Patel", price: 8.0, retained: true },
      { name: "Kamindu Mendis", price: 0.75, retained: true },
      { name: "Brydon Carse", price: 1.0, retained: true },
      { name: "Aniket Verma", price: 0.30, retained: true },
      { name: "Zeeshan Ansari", price: 0.40, retained: true },
      { name: "Jaydev Unadkat", price: 1.0, retained: true },
      { name: "Eshan Malinga", price: 1.20, retained: true },
      { name: "Ravichandran Smaran", price: 0.30, retained: true },
      { name: "Harsh Dubey", price: 0.30, retained: true },
      // 2026 mini auction buys
      { name: "Liam Livingstone", price: 13.0 },
      { name: "Jack Edwards", price: 3.0 },
      { name: "Salil Arora", price: 1.50 },
      { name: "Shivam Mavi", price: 0.75 },
      { name: "Shivang Kumar", price: 0.30 },
      { name: "Sakib Hussain", price: 0.30 },
      { name: "Onkar Tarmale", price: 0.30 },
      { name: "Amit Kumar", price: 0.30 },
      { name: "Praful Hinge", price: 0.30 },
      { name: "Krains Fuletra", price: 0.30 },
    ],
  },
];

// ---------------------------------------------------------------------------
// IPL 2025 Rosters (after Nov 2024 mega auction)
// ---------------------------------------------------------------------------

export const IPL_2025_ROSTERS: IPLRoster[] = [
  {
    teamId: "csk",
    teamName: "Chennai Super Kings",
    shortName: "CSK",
    players: [
      // Retained
      { name: "Ruturaj Gaikwad", price: 18.0, retained: true },
      { name: "Ravindra Jadeja", price: 18.0, retained: true },
      { name: "Matheesha Pathirana", price: 13.0, retained: true },
      { name: "Shivam Dube", price: 12.0, retained: true },
      { name: "MS Dhoni", price: 4.0, retained: true },
      // Auction buys
      { name: "Noor Ahmad", price: 10.0 },
      { name: "Devon Conway", price: 6.25 },
      { name: "Khaleel Ahmed", price: 4.80 },
      { name: "Rachin Ravindra", price: 4.0 },
      { name: "Rahul Tripathi", price: 3.40 },
      { name: "Anshul Kamboj", price: 3.40 },
      { name: "Sam Curran", price: 2.40 },
      { name: "Nathan Ellis", price: 2.0 },
      { name: "Deepak Hooda", price: 1.70 },
      { name: "Jamie Overton", price: 1.50 },
      { name: "Vijay Shankar", price: 1.20 },
      { name: "Ashutosh Sharma", price: 3.80 },
      { name: "Vansh Bedi", price: 0.55 },
      { name: "Shreyas Gopal", price: 0.30 },
      { name: "Mukesh Choudhary", price: 0.30 },
      { name: "Kamlesh Nagarkoti", price: 0.30 },
      { name: "Gurjapneet Singh", price: 2.20 },
      { name: "Ramakrishna Ghosh", price: 0.30 },
      { name: "Andre Siddarth", price: 0.30 },
      { name: "Shaik Rasheed", price: 0.30 },
    ],
  },
  {
    teamId: "dc",
    teamName: "Delhi Capitals",
    shortName: "DC",
    players: [
      // Retained
      { name: "Axar Patel", price: 16.50, retained: true },
      { name: "Kuldeep Yadav", price: 13.25, retained: true },
      { name: "Tristan Stubbs", price: 10.0, retained: true },
      { name: "Abishek Porel", price: 4.0, retained: true },
      // Auction buys
      { name: "KL Rahul", price: 14.0 },
      { name: "Mitchell Starc", price: 11.75 },
      { name: "T Natarajan", price: 10.75 },
      { name: "Jake Fraser-McGurk", price: 9.0 },
      { name: "Mukesh Kumar", price: 8.0 },
      { name: "Harry Brook", price: 6.25 },
      { name: "Ashutosh Sharma", price: 3.80 },
      { name: "Mohit Sharma", price: 2.20 },
      { name: "Faf du Plessis", price: 2.0 },
      { name: "Sameer Rizvi", price: 0.95 },
      { name: "Dushmantha Chameera", price: 0.75 },
      { name: "Donovan Ferreira", price: 0.75 },
      { name: "Karun Nair", price: 0.50 },
      { name: "Vipraj Nigam", price: 0.50 },
      { name: "Madhav Tiwari", price: 0.40 },
      { name: "Ajay Mandal", price: 0.30 },
      { name: "Manvanth Kumar", price: 0.30 },
      { name: "Tripurana Vijay", price: 0.30 },
      { name: "Lhuan-dre Pretorius", price: 0.30 },
      { name: "Darshan Nalkande", price: 0.30 },
      { name: "Mayank Rawat", price: 0.30 },
    ],
  },
  {
    teamId: "gt",
    teamName: "Gujarat Titans",
    shortName: "GT",
    players: [
      // Retained
      { name: "Rashid Khan", price: 18.0, retained: true },
      { name: "Shubman Gill", price: 16.50, retained: true },
      { name: "Sai Sudharsan", price: 8.50, retained: true },
      { name: "Rahul Tewatia", price: 4.0, retained: true },
      { name: "Shahrukh Khan", price: 4.0, retained: true },
      // Auction buys
      { name: "Jos Buttler", price: 15.75 },
      { name: "Mohammed Siraj", price: 12.25 },
      { name: "Kagiso Rabada", price: 10.75 },
      { name: "Prasidh Krishna", price: 9.50 },
      { name: "Washington Sundar", price: 3.20 },
      { name: "Gerald Coetzee", price: 2.40 },
      { name: "Glenn Phillips", price: 2.0 },
      { name: "Sai Kishore", price: 2.0 },
      { name: "Sherfane Rutherford", price: 1.50 },
      { name: "Karim Janat", price: 1.0 },
      { name: "Mahipal Lomror", price: 0.75 },
      { name: "Ishant Sharma", price: 0.75 },
      { name: "Jayant Yadav", price: 0.75 },
      { name: "Manav Suthar", price: 0.30 },
      { name: "Nishant Sindhu", price: 0.30 },
      { name: "Anuj Rawat", price: 0.30 },
      { name: "Kulwant Khejroliya", price: 0.30 },
      { name: "Gurnoor Brar", price: 0.30 },
      { name: "Kumar Kushagra", price: 0.30 },
      { name: "Arshad Khan", price: 0.30 },
    ],
  },
  {
    teamId: "kkr",
    teamName: "Kolkata Knight Riders",
    shortName: "KKR",
    players: [
      // Retained
      { name: "Rinku Singh", price: 13.0, retained: true },
      { name: "Varun Chakravarthy", price: 12.0, retained: true },
      { name: "Sunil Narine", price: 12.0, retained: true },
      { name: "Andre Russell", price: 12.0, retained: true },
      { name: "Harshit Rana", price: 4.0, retained: true },
      { name: "Ramandeep Singh", price: 4.0, retained: true },
      // Auction buys
      { name: "Venkatesh Iyer", price: 23.75 },
      { name: "Anrich Nortje", price: 6.50 },
      { name: "Quinton de Kock", price: 3.60 },
      { name: "Spencer Johnson", price: 2.80 },
      { name: "Rahmanullah Gurbaz", price: 2.0 },
      { name: "Moeen Ali", price: 2.0 },
      { name: "Ajinkya Rahane", price: 1.50 },
      { name: "Rovman Powell", price: 1.50 },
      { name: "Umran Malik", price: 0.75 },
      { name: "Manish Pandey", price: 0.75 },
      { name: "Angkrish Raghuvanshi", price: 0.30 },
      { name: "Vaibhav Arora", price: 0.30 },
      { name: "Anukul Roy", price: 0.30 },
      { name: "Mayank Markande", price: 0.30 },
      { name: "Luvnith Sisodia", price: 0.30 },
    ],
  },
  {
    teamId: "lsg",
    teamName: "Lucknow Super Giants",
    shortName: "LSG",
    players: [
      // Retained
      { name: "Nicholas Pooran", price: 21.0, retained: true },
      { name: "Ravi Bishnoi", price: 11.0, retained: true },
      { name: "Mayank Yadav", price: 11.0, retained: true },
      { name: "Avesh Khan", price: 9.75, retained: true },
      { name: "Ayush Badoni", price: 4.0, retained: true },
      // Auction buys
      { name: "Rishabh Pant", price: 27.0 },
      { name: "David Miller", price: 7.50 },
      { name: "Abdul Samad", price: 4.20 },
      { name: "Mitchell Marsh", price: 3.40 },
      { name: "Shahbaz Ahmed", price: 2.40 },
      { name: "Aiden Markram", price: 2.0 },
      { name: "Mohsin Khan", price: 4.0, retained: true },
      { name: "Manimaran Siddharth", price: 0.75 },
      { name: "Matthew Breetzke", price: 0.75 },
      { name: "Shamar Joseph", price: 0.75 },
      { name: "Arjun Tendulkar", price: 0.30 },
      { name: "Arshin Kulkarni", price: 0.30 },
      { name: "Himmat Singh", price: 0.30 },
      { name: "Akash Singh", price: 0.30 },
      { name: "Prince Yadav", price: 0.30 },
      { name: "Yuvraj Chaudhary", price: 0.30 },
      { name: "Digvesh Rathi", price: 0.30 },
      { name: "Thala Thennarasu", price: 0.30 },
      { name: "Rajvardhan Hangargekar", price: 0.30 },
      { name: "Utkarsh Singh", price: 0.30 },
    ],
  },
  {
    teamId: "mi",
    teamName: "Mumbai Indians",
    shortName: "MI",
    players: [
      // Retained
      { name: "Jasprit Bumrah", price: 18.0, retained: true },
      { name: "Hardik Pandya", price: 16.35, retained: true },
      { name: "Suryakumar Yadav", price: 16.35, retained: true },
      { name: "Rohit Sharma", price: 16.30, retained: true },
      { name: "Tilak Varma", price: 8.0, retained: true },
      // Auction buys
      { name: "Trent Boult", price: 12.50 },
      { name: "Deepak Chahar", price: 9.25 },
      { name: "Naman Dhir", price: 5.25 },
      { name: "Will Jacks", price: 5.25 },
      { name: "Allah Ghazanfar", price: 4.80 },
      { name: "Mitchell Santner", price: 2.0 },
      { name: "Sherfane Rutherford", price: 1.50 },
      { name: "Ryan Rickelton", price: 1.0 },
      { name: "Reece Topley", price: 0.75 },
      { name: "Lizaad Williams", price: 0.75 },
      { name: "Robin Minz", price: 0.65 },
      { name: "Karn Sharma", price: 0.50 },
      { name: "Raghu Sharma", price: 0.50 },
      { name: "Corbin Bosch", price: 0.75 },
      { name: "Raj Bawa", price: 0.30 },
      { name: "Vignesh Puthur", price: 0.30 },
      { name: "Bevon Jacobs", price: 0.30 },
      { name: "Arjun Tendulkar", price: 0.30 },
      { name: "Mohammad Izhar", price: 0.30 },
      { name: "Ashwani Kumar", price: 0.30 },
    ],
  },
  {
    teamId: "pbks",
    teamName: "Punjab Kings",
    shortName: "PBKS",
    players: [
      // Retained
      { name: "Shashank Singh", price: 4.0, retained: true },
      { name: "Prabhsimran Singh", price: 4.0, retained: true },
      // Auction buys
      { name: "Shreyas Iyer", price: 26.75 },
      { name: "Arshdeep Singh", price: 18.0 },
      { name: "Yuzvendra Chahal", price: 18.0 },
      { name: "Marcus Stoinis", price: 11.0 },
      { name: "Marco Jansen", price: 7.0 },
      { name: "Nehal Wadhera", price: 4.20 },
      { name: "Priyansh Arya", price: 3.80 },
      { name: "Josh Inglis", price: 2.60 },
      { name: "Azmatullah Omarzai", price: 2.40 },
      { name: "Lockie Ferguson", price: 2.0 },
      { name: "Vyshak Vijaykumar", price: 1.80 },
      { name: "Yash Thakur", price: 1.60 },
      { name: "Harpreet Brar", price: 1.50 },
      { name: "Aaron Hardie", price: 1.25 },
      { name: "Vishnu Vinod", price: 0.95 },
      { name: "Mitch Owen", price: 1.0 },
      { name: "Xavier Bartlett", price: 0.80 },
      { name: "Kuldeep Sen", price: 0.80 },
      { name: "Harnoor Singh Pannu", price: 0.30 },
      { name: "Musheer Khan", price: 0.30 },
      { name: "Suryansh Shedge", price: 0.30 },
      { name: "Pyla Avinash", price: 0.30 },
      { name: "Pravin Dubey", price: 0.30 },
    ],
  },
  {
    teamId: "rr",
    teamName: "Rajasthan Royals",
    shortName: "RR",
    players: [
      // Retained
      { name: "Sanju Samson", price: 18.0, retained: true },
      { name: "Yashasvi Jaiswal", price: 18.0, retained: true },
      { name: "Riyan Parag", price: 14.0, retained: true },
      { name: "Dhruv Jurel", price: 14.0, retained: true },
      { name: "Shimron Hetmyer", price: 11.0, retained: true },
      { name: "Sandeep Sharma", price: 4.0, retained: true },
      // Auction buys
      { name: "Jofra Archer", price: 12.50 },
      { name: "Tushar Deshpande", price: 6.50 },
      { name: "Wanindu Hasaranga", price: 5.25 },
      { name: "Maheesh Theekshana", price: 4.40 },
      { name: "Nitish Rana", price: 4.20 },
      { name: "Fazalhaq Farooqi", price: 2.0 },
      { name: "Kwena Maphaka", price: 1.50 },
      { name: "Akash Madhwal", price: 1.20 },
      { name: "Vaibhav Suryavanshi", price: 1.10 },
      { name: "Shubham Dubey", price: 0.80 },
      { name: "Yudhvir Singh Charak", price: 0.35 },
      { name: "Kumar Kartikeya Singh", price: 0.30 },
      { name: "Kunal Rathore", price: 0.30 },
      { name: "Nandre Burger", price: 3.50 },
      { name: "Lhuan-dre Pretorius", price: 0.30 },
      { name: "Ashok Sharma", price: 0.30 },
      { name: "Ozzie Balderson", price: 0.30 },
      { name: "Jehan Daniel", price: 0.30 },
      { name: "Ravi Singh", price: 0.30 },
    ],
  },
  {
    teamId: "rcb",
    teamName: "Royal Challengers Bengaluru",
    shortName: "RCB",
    players: [
      // Retained
      { name: "Virat Kohli", price: 21.0, retained: true },
      { name: "Rajat Patidar", price: 11.0, retained: true },
      { name: "Yash Dayal", price: 5.0, retained: true },
      // Auction buys
      { name: "Josh Hazlewood", price: 12.50 },
      { name: "Phil Salt", price: 11.50 },
      { name: "Jitesh Sharma", price: 11.0 },
      { name: "Bhuvneshwar Kumar", price: 10.75 },
      { name: "Liam Livingstone", price: 8.75 },
      { name: "Rasikh Dar Salam", price: 6.0 },
      { name: "Krunal Pandya", price: 5.75 },
      { name: "Tim David", price: 3.0 },
      { name: "Jacob Bethell", price: 2.60 },
      { name: "Suyash Sharma", price: 2.60 },
      { name: "Devdutt Padikkal", price: 2.0 },
      { name: "Lungi Ngidi", price: 2.0 },
      { name: "Nuwan Thushara", price: 1.60 },
      { name: "Romario Shepherd", price: 1.50 },
      { name: "Swapnil Singh", price: 0.50 },
      { name: "Swastik Chikara", price: 0.30 },
      { name: "Abhinandan Singh", price: 0.30 },
      { name: "Manoj Bhandage", price: 0.30 },
      { name: "Dan Mousley", price: 0.30 },
      { name: "Mohit Rathee", price: 0.30 },
      { name: "Rajan Kumar", price: 0.30 },
      { name: "Saurav Chauhan", price: 0.30 },
    ],
  },
  {
    teamId: "srh",
    teamName: "Sunrisers Hyderabad",
    shortName: "SRH",
    players: [
      // Retained
      { name: "Heinrich Klaasen", price: 23.0, retained: true },
      { name: "Pat Cummins", price: 18.0, retained: true },
      { name: "Abhishek Sharma", price: 14.0, retained: true },
      { name: "Travis Head", price: 14.0, retained: true },
      { name: "Nitish Kumar Reddy", price: 6.0, retained: true },
      // Auction buys
      { name: "Ishan Kishan", price: 11.25 },
      { name: "Harshal Patel", price: 8.0 },
      { name: "Abhinav Manohar", price: 3.20 },
      { name: "Rahul Chahar", price: 3.20 },
      { name: "Adam Zampa", price: 2.40 },
      { name: "Simarjeet Singh", price: 1.50 },
      { name: "Eshan Malinga", price: 1.20 },
      { name: "Brydon Carse", price: 1.0 },
      { name: "Jaydev Unadkat", price: 1.0 },
      { name: "Kamindu Mendis", price: 0.75 },
      { name: "Hasaranga de Silva", price: 0.75 },
      { name: "Zeeshan Ansari", price: 0.40 },
      { name: "Atharva Taide", price: 0.30 },
      { name: "Aniket Verma", price: 0.30 },
      { name: "Sachin Baby", price: 0.30 },
      { name: "Ravichandran Smaran", price: 0.30 },
      { name: "Mulveer Singh Rathore", price: 0.30 },
      { name: "Aunkit Rajput", price: 0.30 },
    ],
  },
];
